#!/usr/bin/env bash
set -euo pipefail

STATUS_FILE="${1:-artifacts/local-status.env}"
OUTPUT_FILE="${2:-artifacts/local-controls-summary.md}"

mkdir -p "$(dirname "${OUTPUT_FILE}")"

if [[ -f "${STATUS_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${STATUS_FILE}"
fi

: "${PIPELINE_MODE:=manual-summary}"
: "${GENERATED_AT:=$(date -u +'%Y-%m-%d %H:%M:%SZ')}"
: "${LINT_STATUS:=not-run}"
: "${TEST_STATUS:=not-run}"
: "${COVERAGE_STATUS:=not-run}"
: "${COVERAGE_PERCENT:=not-available}"
: "${COVERAGE_THRESHOLD:=85}"
: "${SAST_STATUS:=not-run}"
: "${DEPENDENCY_STATUS:=not-run}"
: "${SECRETS_STATUS:=not-run}"
: "${CONTAINER_BUILD_STATUS:=not-run}"
: "${CONTAINER_SCAN_STATUS:=not-run}"
: "${FINAL_GATE_RESULT:=not-run}"
: "${FINAL_GATE_NOTE:=No gate result recorded.}"

if [[ "${COVERAGE_PERCENT}" == "not-available" ]]; then
  COVERAGE_DISPLAY="not available"
else
  COVERAGE_DISPLAY="${COVERAGE_PERCENT}%"
fi

format_status() {
  case "$1" in
    passed)
      echo "PASS"
      ;;
    failed)
      echo "FAIL"
      ;;
    partial)
      echo "PARTIAL"
      ;;
    not-run)
      echo "NOT RUN"
      ;;
    not-available)
      echo "N/A"
      ;;
    *)
      echo "$1"
      ;;
  esac
}

cat > "${OUTPUT_FILE}" <<EOF
# Local Controls Summary

This file is generated by \`scripts/generate_local_summary.sh\`.

- Mode: \`${PIPELINE_MODE}\`
- Generated at: \`${GENERATED_AT}\`

| Control | Status | Evidence | Gate behavior |
| --- | --- | --- | --- |
| Ruff quality gate | $(format_status "${LINT_STATUS}") | \`reports/lint.txt\` | Blocks on any lint finding |
| Pytest suite | $(format_status "${TEST_STATUS}") | \`reports/pytest.txt\`, \`reports/junit.xml\` | Blocks on any failing unit or API test |
| Coverage gate | $(format_status "${COVERAGE_STATUS}") | \`coverage.xml\` | Blocks below ${COVERAGE_THRESHOLD}% |
| Coverage result | ${COVERAGE_DISPLAY} | \`coverage.xml\` | Informational representation of the last run |
| SAST controls | $(format_status "${SAST_STATUS}") | \`reports/bandit.json\`, \`reports/semgrep.json\` | Full pipeline blocks on Bandit high findings or curated Semgrep hits |
| Dependency scan | $(format_status "${DEPENDENCY_STATUS}") | \`reports/pip-audit.json\` | Full pipeline blocks on known vulnerable packages |
| Secret scan | $(format_status "${SECRETS_STATUS}") | \`reports/gitleaks.sarif\` | Full pipeline blocks on any detected secret |
| Container build | $(format_status "${CONTAINER_BUILD_STATUS}") | \`reports/docker-build.txt\` | Required before image scanning |
| Container scan | $(format_status "${CONTAINER_SCAN_STATUS}") | \`reports/trivy-image.json\`, \`reports/container-scan.txt\` | Full pipeline blocks on HIGH/CRITICAL findings with fixes available |

## Final gate result

- Result: \`$(format_status "${FINAL_GATE_RESULT}")\`
- Note: ${FINAL_GATE_NOTE}

## Recommended files to open next

- \`README.md\`
- \`.github/workflows/ci.yml\`
- \`docs/security-policy.md\`
- \`docs/examples/sample-ci-summary.md\`
- \`docs/examples/sample-container-scan-summary.md\`
EOF

echo "${OUTPUT_FILE}"
